# Generated by Django 4.0.6 on 2022-08-04 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('seminar', '0001_initial'), ('seminar', '0002_userseminar'), ('seminar', '0003_seminar_nullable_capacity'), ('seminar', '0004_seminar_blankable_capacity'), ('seminar', '0005_seminar_blankable_desc')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nullable_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('blankable_capacity', models.PositiveIntegerField(blank=True, default=0)),
                ('blankable_desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSeminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar.seminar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
