# Generated by Django 4.0.6 on 2022-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_squashed_0005_seminar_blankable_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='type',
            field=models.CharField(choices=[('1', '세미나'), ('2', '스터디')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='blankable_capacity',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
