# Generated by Django 4.0.6 on 2022-08-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_seminar_type_alter_seminar_blankable_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='blankable_capacity',
        ),
    ]
