# Generated by Django 4.0.6 on 2022-08-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_remove_seminar_blankable_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='blankable_desc',
        ),
    ]
