# Generated by Django 4.0.6 on 2022-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_seminar_nullable_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='blankable_capacity',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
